#!/bin/bash
#   ( РОДИТЕЛЬ | КЛАВИША | НАЗВАНИЕ | ФУНКЦИЯ | ПОРЯДОК | ГРУППА | ОПИСАНИЕ )
# @menu.manifest
# @item( security | 3 | 🧠 Kernel Hardening | show_kernel_menu | 30 | 10 | Усиление защиты ядра от сетевых атак. )
#
# kernel.sh - Kernel Hardening (sysctl)
#

SYSCTL_CONF_FILE="/etc/sysctl.d/99-reshala-hardening.conf"

show_kernel_menu() {
    while true; do
        clear
        enable_graceful_ctrlc
        menu_header "🧠 Kernel Hardening"
        printf_description "Усиление защиты и оптимизация ядра"

        _kernel_check_status
        
        echo ""
        printf_menu_option "1" "Применить безопасные настройки"
        printf_menu_option "2" "Откатить изменения"
        echo ""
        printf_menu_option "b" "Назад"
        echo ""

        local choice
        choice=$(safe_read "Выберите действие" "") || { break; }
        
        case "$choice" in
            1) _kernel_apply; wait_for_enter;;
            2) _kernel_revert; wait_for_enter;;
            b|B) break;;
            *) warn "Неверный выбор";;
        esac
        disable_graceful_ctrlc
    done
}

_kernel_check_status() {
    print_separator
    info "Статус Kernel Hardening"

    if [[ -f "$SYSCTL_CONF_FILE" ]]; then
        printf_description "Конфиг: ${C_GREEN}Применен${C_RESET} ($SYSCTL_CONF_FILE)"
        
        # Проверяем ключевые параметры
        local syn_cookies
        syn_cookies=$(run_cmd sysctl -n net.ipv4.tcp_syncookies 2>/dev/null)
        
        local rp_filter
        rp_filter=$(run_cmd sysctl -n net.ipv4.conf.all.rp_filter 2>/dev/null)
        
        local aslr
        aslr=$(run_cmd sysctl -n kernel.randomize_va_space 2>/dev/null)

        echo ""
        info "Ключевые параметры:"
        
        [[ "$syn_cookies" == "1" ]] && printf_description "  - SYN Cookies: ${C_GREEN}Включены${C_RESET}" || printf_description "  - SYN Cookies: ${C_RED}Отключены${C_RESET}"
        [[ "$rp_filter" == "1" ]] && printf_description "  - RP Filter (Anti-Spoofing): ${C_GREEN}Включен${C_RESET}" || printf_description "  - RP Filter (Anti-Spoofing): ${C_RED}Отключен${C_RESET}"
        [[ "$aslr" == "2" ]] && printf_description "  - ASLR (Address Space Randomization): ${C_GREEN}Полный${C_RESET}" || printf_description "  - ASLR (Address Space Randomization): ${C_YELLOW}Частичный или выкл${C_RESET}"

    else
        printf_description "Конфиг: ${C_YELLOW}Не применялся${C_RESET}"
    fi
    print_separator
}

_kernel_apply() {
    print_separator
    info "Применение Kernel Hardening"
    print_separator

    if ! ask_yes_no "Это действие создаст файл $SYSCTL_CONF_FILE и применит системные настройки. Продолжить?"; then
        info "Отмена."
        return
    fi
    
    local backup_dir
    backup_dir="${SCRIPT_DIR}/modules/security/backups"
    run_cmd mkdir -p "$backup_dir"
    
    info "Создаю бэкап текущих sysctl настроек..."
    run_cmd sysctl -a > "$backup_dir/sysctl.backup_$(date +%s)" 2>/dev/null
    ok "Бэкап создан в $backup_dir"

    info "Создаю конфигурационный файл..."
    run_cmd tee "$SYSCTL_CONF_FILE" > /dev/null << 'SYSCTL'
# Generated by Reshala Security Module
#
# Kernel Hardening & Performance Tuning
#

# --- SYN Flood Protection ---
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_max_syn_backlog = 4096
net.core.somaxconn = 4096
net.core.netdev_max_backlog = 4096

# --- IP Spoofing & Network Attack Protection ---
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# --- TCP Tuning ---
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# --- Kernel Security ---
kernel.randomize_va_space = 2
kernel.dmesg_restrict = 1
kernel.yama.ptrace_scope = 1
fs.protected_symlinks = 1
fs.protected_hardlinks = 1

# IP Forwarding is intentionally left untouched for VPN compatibility
SYSCTL
    
    ok "Конфигурационный файл создан."
    
    info "Применяю настройки..."
    if run_cmd sysctl -p "$SYSCTL_CONF_FILE"; then
        ok "Настройки Kernel Hardening успешно применены."
    else
        err "Произошла ошибка при применении настроек."
    fi
}

_kernel_revert() {
    print_separator
    info "Откат Kernel Hardening"
    print_separator
    
    if [[ ! -f "$SYSCTL_CONF_FILE" ]]; then
        warn "Настройки Kernel Hardening не применялись (файл не найден)."
        return
    fi
    
    if ! ask_yes_no "Это действие удалит файл $SYSCTL_CONF_FILE и вернет стандартные системные настройки. Продолжить?"; then
        info "Отмена."
        return
    fi
    
    info "Удаляю конфигурационный файл..."
    run_cmd rm -f "$SYSCTL_CONF_FILE"
    
    info "Перезагружаю системные правила sysctl..."
    if run_cmd sysctl --system; then
        ok "Настройки Kernel Hardening откачены."
    else
        err "Произошла ошибка при откате настроек."
    fi
}
