#!/bin/bash
#
# TITLE: (System) Apply Kernel Hardening
# SKYNET_HIDDEN: true
#
# Применяет безопасные настройки sysctl на удаленном сервере.

# --- Standard helpers for Skynet plugins ---
set -e # Exit immediately if a command exits with a non-zero status.
C_RESET='\033[0m'; C_RED='\033[0;31m'; C_GREEN='\033[0;32m'; C_YELLOW='\033[1;33m';
info() { echo -e "${C_RESET}[i] $*${C_RESET}"; }
ok()   { echo -e "${C_GREEN}[✓] $*${C_RESET}"; }
warn() { echo -e "${C_YELLOW}[!] $*${C_RESET}"; }
err()  { echo -e "${C_RED}[✗] $*${C_RESET}"; exit 1; }
# --- End of helpers ---

info "Применяю настройки безопасности ядра (Kernel Hardening)..."

SYSCTL_CONF_FILE="/etc/sysctl.d/99-reshala-hardening.conf"

# Создаём конфиг
tee "$SYSCTL_CONF_FILE" > /dev/null << 'SYSCTL'
# Generated by Reshala Security Module
#
# Kernel Hardening & Performance Tuning
#

# --- SYN Flood Protection ---
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_max_syn_backlog = 4096
net.core.somaxconn = 4096
net.core.netdev_max_backlog = 4096

# --- IP Spoofing & Network Attack Protection ---
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# --- TCP Tuning ---
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# --- Kernel Security ---
kernel.randomize_va_space = 2
kernel.dmesg_restrict = 1
kernel.yama.ptrace_scope = 1
fs.protected_symlinks = 1
fs.protected_hardlinks = 1
SYSCTL

ok "Конфигурационный файл создан: $SYSCTL_CONF_FILE"

info "Применяю настройки..."
if ! sysctl -p "$SYSCTL_CONF_FILE" >/dev/null; then
    err "Произошла ошибка при применении настроек sysctl."
fi

ok "Настройки безопасности ядра успешно применены."

exit 0
